RedHatInsights/ccx-notification-service

- go.mod
- producer/producer.go
- producer/producer_test.go
basic kafka producer whose broker and production topic can be configured using the tool file.
UTs + local kafka instance test
> Adding basic Kafka producer

- PoC-differ/config.toml
- PoC-differ/content.go
- PoC-differ/differ.go
- conf/config.go
- types/types.go
Remove parsing from content directory and fetch rules content from content service API instead.
Fixes #31
- This change requires a documentation update
Manual test of differ service.
> Fetch rules content from content-service

- PoC-differ/config.toml
- PoC-differ/config_ci.toml
- PoC-differ/config_prod.toml
- PoC-differ/config_stage.toml
- PoC-differ/content.go
- PoC-differ/differ.go
- conf/config.go
- producer/producer.go
- producer/producer_test.go
- types/types.go
Incomplete but working version of the notification service.
- Config files have been cleaned up. Removed values are expected to be set in deployment environment.
- Differ produces 1 notification per cluster with important and critical issues.
- Updated constants for notification message (fields expected by the email template and such)
- Use the timestamp of the selected reports as timestamp for the notified issues
- Notify issues with total risk higher or equal to 3 instead of 2
- Make the notification message comply with the expected format (JSON string with escaped strings inside) 
- Fix some errors in the code (e.g Kafka producer was set and closed for each cluster), added some error control and basic logging.
- Added TODOs for code that is part of other tasks
Fixes #28 
- Bug fix …
> Notification service v1

- PoC-differ/differ.go
- PoC-differ/storage.go
- types/types.go
We now retrieve account number for each report in addition to cluster name and org_id, and use it to notify the correct customer.
Fixes #30 
- This change requires a documentation update
Manual testing, populating DB with three entries corresponding to two different accounts to verify instant notifications and weekly notifications behavior.
> Retrieve correct account number from DB

- ccx_notification_service.go
- differ/differ.go
Rename differ's Init function to avoid mixups with Go's init
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.
> Rename differ's Init function to avoid mixups with Go's init

- differ/storage.go
- tests/mocks/Storage.go
Ability to delete old reports for given organization on demand
Fixes #35
N/A
> Ability to delete old reports for given organization on demand

- differ/differ.go
Messages received in ccx-op-results in the QA env are all associated to the same account number.
This commit redirects those messages so that emails are not sent to the corresponding user's email.
Not tested.
> Temporarily redirect messages to pcamara's account number

- differ/differ.go
- differ/differ_test.go
This PR lets URIs for links included in notification be configured directly via environment variables. This is so while I figure out how to get all the necessary information to create the final URLs, we can redirect to the cluster overview or a similar page that actually exists.
- other
UTs and manual test
> Set notification URLs directly from env variables

- config-devel.toml
- differ/differ.go
- differ/differ_test.go
Update the cluster URL and rules URLs to the new requirements. Also added a `config-devel.toml` to make the development process easier.
Fixes #110
Ran a local setup with Kafka+PostgreSQL, `insights-content-service` and `ccx-notification-writer`. Publish some risk-3 messages to Kafka and check that the URLs match the requirements. For example:
```json
{
"bundle": "openshift",
"application": "advisor",
"event_type": "new-recommendation",
"timestamp": "2021-08-17T13:37:00Z",
"account_id": "6089719",
"events": [
{
"metadata": {},
"payload": "{\"publish_date\":\"2021-08-17T15:36:42.749512Z\",\"rule_description\":\"node_installer_degraded\",\"rule_url\":\"https://console.redhat.com/openshift/details …
```
> Update hitting recommendations URLs

- docs/local_setup.md
I added a local setup guide to reproduce how this service works and connects with the rest of services, including `insights-results-aggregator-data`, `insights-results-aggregator-utils`, `insights-content-service`and `notificatios-backend`.
Feel free to add anything if you think I miss something.
> Added a local setup page

- differ/differ.go
- differ/differ_test.go
Small change in the instant notification's payload to display rule's description instead of title.
CI
> Display rule's description instead of title in instant notifications

- README.md
- abcgo.sh
- differ/cleaner.go
- differ/differ.go
- differ/storage.go
- tests/mocks/Storage.go
- types/types.go
Ability to display and cleanup old DB records
Fixes #121
N/A
> Ability to display and cleanup old DB records

- README.md
- abcgo.sh
- conf/config.go
- config-devel.toml
- config.toml
- differ/cleaner.go
- differ/differ.go
- gocyclo.sh
- tests/config2.toml
- types/types.go
Ability to cleanup DB on startup
Fixes #120
N/A
> Ability to cleanup DB on startup

- conf/config.go
- conf/configuration_test.go
- config.toml
- differ/differ.go
- differ/metrics.go
- differ/metrics_test.go
- tests/config2.toml
The notification service is deployed as a cronjob. Since it is a short-lived job, using polling to collect the metrics is not the best choice as the time series can have a lot of missing points if the polling doesn't happen when the job is alive.
- The metrics configuration has been updated to include:
- the push gateway URL
- the required information to group our metrics as expected by app-sre
Fixes #132
- This change requires a documentation update
Added some unit tests, but prometheus push gateway has been tested locally with a push gateway instance.
> Push prometheus metrics to push gateway instead of waiting for polling

- go.mod
- go.sum
Bump-up `utils` repository to 1.14.0
Fixes #134
- Bump-up dependency
N/A
> Bump-up `utils` repository to 1.14.0

- differ/content.go
- differ/differ.go
- differ/differ_test.go
- go.mod
- go.sum
- types/types.go
When insights-operator.utils structs are updated, ccx-notification-service types need to be updated manually to keep up with it. This change fixes that, and fixes the current issue with the impact field of the error_key metadata.
A struct { Name, Impact } is now expected in impact fiel, instead of a string.
local testing + CI
> Remove duplicated types and update related code

- conf/config.go
- config.toml
- differ/differ.go
- differ/differ_test.go
Sometimes, the CCX Notification service cronjob exits with an error, when what happens is that the metrics couldn't be pushed. With this change, a retrial mechanism can be enabled (number of attempts and how much to wait between each attempt).
Fixes CCXDEV-6557
Tested locally with prometheus push gateway (available, not available, and returning 502)
> [CCXDEV-6557] Add retry mechanism for pushed metrics

- differ/comparator.go
- differ/comparator_test.go
- differ/differ.go
- differ/differ_test.go
- differ/storage.go
This service is taking way more time than expected when dealing with our production data. These "small" optimisations aim to improve its performance  by reducing to a minimum the amount of work done. The idea is to decide if there is a need to introduce concurrency  AFTER verifying the improvements in production.
- Updated existing UTs and validated new behaviour through previously tested scenarios 
- `make bdd_tests` passes
- Each commit of this PR has been tested and benchmarked separately to see if it optimises the processing or not.
> Performance optimizitations round 1

- differ/differ.go
- differ/differ_test.go
The total risk of a given issue still needs to be calculated. The field added to the error key structure is just a placeholder that is currently being filled by the smart-proxy, not the insights-content-service itself.
(Fix issue detected in stage env when delivered)
Local testing + UTs
> Restore total risk calculation

- differ/comparator.go
- differ/comparator_test.go
- differ/differ_test.go
This part of the code was bug-prone, but couldn't be tested with UTs.
By adding the `getNotificationResolution` function, we can add UTs that verify the expected behaviour when using the cool down mechanism.
Added UTs
> Refactor shouldNotify function to improve coverage

- differ/comparator.go
- differ/comparator_test.go
- differ/differ_test.go
- differ/storage.go
- tests/mocks/Storage.go
This commit includes two fixes:
- When comparing timestamp from time.Now() with the timestamp stored in the database, there is a discrepancy created by the fact that time.Now() contains the local timezone info, while the other timestamp does not.
- When comparing current issues with previously notified reports, we should compare with the latest entry with `state=sent`.
Fixes CCXDEV-7026
Updated corresponding UTs
> Compare current reports with reports with state=sent from reported

- deploy/ccx-notification-service.yaml
In stage env our completed cronjobs are counted into the CPU/mem quota. To not count the cronjobs into the quota, we need to use activeDeadlineSeconds for cronjobs to not count the completed jobs into quota.
The activeDeadlineSeconds stops a pod after the specified timeout if it does not complete earlier.
> [CCXDEV-7402] Fix random cpu limit on stage

- differ/differ.go
- differ/differ_test.go
- docs/index.md
- types/types.go
As part of the EBS account number deprecation, the notification backend is currently requiring its clients to send both the org_id and the account number (account number will be removed later).
([We have a Kafka message example with the org ID field here](https://core-platform-apps.pages.redhat.com/notifications-docs/dev/user-guide/send-notification.html#_kafka))
Added UTs + run service locally with all dependencies to check behavior
> [CCXDEV-8800] Include org_id field in the generated event for instant reports

- differ/content.go
- differ/differ_test.go
- go.mod
- go.sum
- types/types.go
Bump-up utils package to 1.23.9
Done on CI I hope
> Bump-up utils package to 1.23.9

- deploy/clowdapp.yaml
Update the job name. Instead of `instance`, let's call it `to-notification-backend`. This way, the job name in OCP will be 
```ccx-notification-service-to-notifications-backend-{TIMESTAMP}``` 
instead of 
```ccx-notification-service-instance-{TIMESTAMP}```
This will be useful for having more than 1 jobs under this clowdapp (f.e [integration with service log](https://issues.redhat.com/browse/CCXDEV-8370)).
Fixes #[CCXDEV-8784](https://issues.redhat.com/browse/CCXDEV-8784)
None.
> [CCXDEV-8784] Update job name

- Dockerfile
This is intended to not needing to set aaaaall the env variables.
> Copy config to docker image

- differ/differ.go
- differ/evaluator_test.go
Refactored out filtering
Basically the most important functions in `differ.go` code use global module variables so it's quite hard to cover them correctly by using unit tests. It would be nice to refactore such long and complicated code. This is the first attempt, just for the filter. The refactored function is isolated from global module variables and thus testable.
Done on CI
> Refactored out filtering

- conf/config.go
- conf/configuration_test.go
- config-devel.toml
- config.toml
- tests/config2.toml
Add url, access_token and timeout to service_log configuration.
Fixes #CCXDEV-8755
BDD tests: https://github.com/RedHatInsights/insights-behavioral-spec/pull/116
> [CCXDEV-8755] Add url, access_token and timeout to service_log configuration

- deploy/clowdapp.yaml
Make max_age for cleanup configurable in deployment file, so we can configure it in each environment
N/A
> Make max_age for cleanup configurable in deployment file

- deploy/clowdapp.yaml
Max age is not properly set if not enclosed in quote
Launched locally
> Fix typo in start command

- differ/differ.go
- differ/differ_test.go
- producer/kafka_producer.go
- producer/producer.go
- producer/producer_test.go
Changes the `Producer` interface so that it does not refer to configuration specific to Kafka producer anymore.
[https://issues.redhat.com/browse/CCXDEV-8780](https://issues.redhat.com/browse/CCXDEV-8780)
Run the unit tests, run with sample data in local setup.
> Make producer interface more flexible

- deploy/clowdapp.yaml
This reverts commit ba6ca40a3d947a06982dc3d821dbf4321b61a750.
Clean up of data older than 8 days in `reported` and `new_reports` table will now be executed before each run
> Revert "do not cleanup on startup"

- deploy/clowdapp.yaml
Augment cronjob's deadline to ensure it does not die continuously during notification DB migration.
> Temporaly augment cronjob's deadline to 5 hours for DB migration

- deploy/clowdapp.yaml
Reverts RedHatInsights/ccx-notification-service#247
> Revert "Temporaly augment cronjob's deadline to 5 hours for DB migration"

- differ/differ.go
- differ/differ_test.go
- producer/disabled_producer.go
- producer/disabled_producer_test.go
Don't send any message if Kafka is disabled.
Unit tests.
> [CCXDEV-8782] Disable kafka

- differ/storage.go
- tests/mocks/Storage.go
- types/types.go
I'm splitting https://github.com/RedHatInsights/ccx-notification-service/pull/243 into smaller pieces. This one adds the `event_target_id` value in the database as a new type, instead of using an int.
Part of #CCXDEV-8782
BDD testing + unit testing.
> [CCXDEV-8782] Add the new types

- conf/config.go
Security protocol value from Clowder is not being propagated to our configuration struct.
> Fix security protocol value propagation from clowder

- differ/comparator.go
- differ/comparator_test.go
- differ/differ.go
- differ/differ_test.go
- differ/export_test.go
- differ/storage.go
- differ/storage_test.go
- go.mod
- go.sum
- tests/mocks/Storage.go
I'm splitting https://github.com/RedHatInsights/ccx-notification-service/pull/243 into smaller pieces.
These changes uses the `types.NotificationBackendTarget` type in order to `ReadLastNotifiedRecordForClusterList` but just for the notification backend. It's a first step before listing the last notified records for service log.
Unit tests + BDD tests.
> [CCXDEV-8782] Use the new type

- docs/index.md
Mention the need to use the ccx-notification-service account in the end to end data flow docs.
> Mention ccx-notification-service account credentials in the docs

- CODEOWNERS
- conf/config.go
- conf/configuration_test.go
Add support for Clowder topics mapping in order to update the topic configuration of the job.
Fixes [#CCXDEV-9200](https://issues.redhat.com/browse/CCXDEV-9200)
Unit tests, local tests
> Add Clowder topics mapping support in configuration load

- differ/comparator.go
- differ/differ.go
- differ/differ_test.go
- differ/storage.go
- producer/disabled/disabled_producer.go
- tests/mocks/Storage.go
More info in [Slack](https://coreos.slack.com/archives/C01A4DTTZN1/p1662387128250149).
Basically, when the notification-service encounters an issue that has to be notified it [updates the DB with sent state](https://github.com/RedHatInsights/ccx-notification-service/blob/68b58b8f4f8d28e1ef8e7712fccdadb0c78e67e3/differ/differ.go#L392), although it doesn't publish anything.
I added some changes in the code to:
* Use a new parameter in the function updateNotificationRecordSentState(storage, cluster, report, notifiedAt) being the eventTarget in order to update the DB accordingly
* Use updateNotificationRecordSentState just if the producer is enabled. I did this by checking the returned offset and setting the offset for the disabled producer to `-1`.
- Bug fix (non-breaking change which fixes …
> [CCXDEV-9220] Don't update reported table if producer is disabled

- conf/config.go
- conf/configuration_test.go
- config-devel.toml
- config.toml
- deploy/clowdapp.yaml
- tests/config2.toml
Access token for acessing Service Log API needs to be periodically refreshed, therefore access token is replaced with offline token and URL to token refreshment API.
Run unit tests.
> Change service log configuration to include info for token refreshment

- differ/differ.go
- differ/differ_test.go
While processing cluster entries, it can happen that we try to read a report that is empty or cannot be deserialised into the [Report structure](https://github.com/RedHatInsights/ccx-notification-service/blob/master/types/types.go#L148). When that happens, we should simply skip that entry and process the next one instead of exiting.
Fixes CCXDEV-9230
- Running existing UTs
- test with local DB using new report with empty value in report column (creating BDD for this)
- test with local DB using new report with some fields but no reports  (creating BDD for this)
> Do not exit cluster entry processing if report not read

- differ/differ.go
- differ/differ_test.go
Log how many cluster entries have not been processed before exiting the processReportsByCluster loop
Updated UTs
> Add extra log for skipped cluster entries

- deploy/clowdapp.yaml
Removing the clean up operation from service log.
We have both service log and notification backend jobs stuck in stage because this operation is too heavy and blocking, so when one is deleting the other is blocked. 
This was detected because the crontab was set each 3 minutes (which is the schedule for stage - it was a typo). The jobs started at the same time and the DB got exhausted. Now the jobs run every 15 minutes each, but the service log one starting at minute 8, so this shouldn't happen again.
However, when prod is updated and the cronjobs restarted, the first run is at the same time, so this change is still necessary.
None.
> Remove cleanup operation from service log

- conf/config.go
- config-devel.toml
- config.toml
- deploy/clowdapp.yaml
- differ/differ_test.go
- differ/renderer.go
- differ/renderer_test.go
- types/types.go
Adds a `differ/renderer.go` file containing functionality for renderering content templates by sending requests to `content-template-renderer` service. This functionality is necessary for Service Log integration
Functionality is not yet integrated with the rest of the code, but has been successfully used locally with modified `differ/differ.go` and additional test has been created for `renderer.go`.
> Add functions for processing content templates

- differ/differ.go
- differ/differ_test.go
Some variables and functions related to Kafka notifier dot not have names specific to Kafka. Changes in this PR rename these, so that the Service Log notifier related things can be introduced. 
N/A
> Rename variables and functions related to Kafka notifier to be specific

- differ/differ.go
- differ/differ_test.go
`processReportsByCluster` is long function, which will contain more functionality in the future (Service Log intergration). This is a small refactor to prepare this function for such changes.
N/A
> Extract function from processReportsByCluster

- differ/differ.go
- differ/differ_test.go
- go.mod
- types/types.go
Include sending messages to service log as a part of `differ.go`. Before enabling this feature in configuration, content-template-renderer service needs to be deployed.
Tried changes locally, added new test.
> Service Log integration

- deploy/clowdapp.yaml
The credentials needed to connect to OCM gateway are stored in vault. This allows the cronjob to retrieve them.
N/A
> Add OCM client credentials to environment variables for service log job

- Makefile
- conf/config.go
- config-devel.toml
- config.toml
- deploy/clowdapp.yaml
- differ/differ.go
- differ/metrics.go
- differ/metrics_test.go
Differentiate the metrics between Service Log and Notification Backend targets by using prometheus metrics subsystems. This way we can differentiate between the two jobs.
If the subsystem is not set, the metric is just the `namespace + _ + name`, just as it's now.
Fixes #CCXDEV-9219
Locally checked the push gateway requests.
> [CCXDEV-9219] Differentiate the metrics between SL and NB targets

- differ/differ.go
- ocmclient/ocmclient.go
- producer/servicelog/service_log_producer.go
- The 'Kafka producer ready' message was showing even when the Kafka producer is disabled. 
- Added info logs to indicate token refreshment is ongoing
N/A
> Small logging improvements

- differ/differ_test.go
Make sure `server.Close()` is called even when error occurs
Done on CI
> Make sure `server.Close()` is called even when error occurs

- differ/differ.go
- differ/differ_test.go
- differ/storage.go
- types/types.go
Avoid doing reports processing and other operations if not necessary:
- If no valid destination is configured, abort differ
- If Kafka broker is not enabled, do not enter in the `produceEntriesToKafka` function
- Refactor
- tested service locally
- Updated UTs
> Do not work if destination not set

- differ/differ.go
In stage we found:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xe78fc6]
goroutine 1 [running]:
github.com/RedHatInsights/ccx-notification-service/differ.closeNotifier(0x0, 0x0, 0x3c, 0xc000248180)
/opt/app-root/src/differ/differ.go:940 +0x26
github.com/RedHatInsights/ccx-notification-service/differ.closeDiffer(0xc0002569f0)
/opt/app-root/src/differ/differ.go:1069 +0x165
github.com/RedHatInsights/ccx-notification-service/differ.startDiffer(0x1, 0xc000043248, 0x4, 0xc00003e4ad, 0x8, 0xc00037e540, 0x8, 0xc0002b2390, 0x14, 0xc0002862d0, ...)
/opt/app-root/src/differ/differ.go:1045 +0x947
github.com/RedHatInsights/ccx-notification-service/differ.Run()
/opt/app-root/src/differ/differ.go:1172 +0x7ef …
```
> initialize producers

- differ/differ.go
- differ/differ_test.go
- `skippedEntries` can grow really fast with the way it is currently calculated, and therefore looses its purpose.
- check possible error and total messages 'sent' in `TestProduceEntriesToServiceLog`
- Updated UTs
> Small differ improvements

- dashboards/grafana-dashboard-ccx-notification-service.configmap.yaml
This is needed because the SL job is taking more than 15 minutes to complete, so the rate (difference between time slides of 15 minutes) is always 0. Increasing it to 1h should be fine.
<details>
<summary>Before:</summary>
<br>
</details>
<details>
<summary>After:</summary>
<br>
</details>
> [Dashboard] Increase the rate range so that SL metrics are shown

- conf/config.go
Avoid NPE when Clowder config is not completed
Done on CI, but partially ATM.
> Avoid NPE when Clowder config is not completed

- differ/differ.go
- differ/metrics.go
- producer/servicelog/service_log_producer.go
The Service Log API can sometimes return status 429 - Too Many Requests when receiving a grand number of events. This change handles that, and avoid recreating the HTTP request every time we need to retry it.
Stage will tell us
> Retry POST after 1 second cooldown when status 429 received

- differ/differ.go
- differ/metrics.go
- producer/servicelog/service_log_producer.go
Reverts RedHatInsights/ccx-notification-service#340
Turns out the ServiceLog API bans the origin of the requests for an hour, so no retries.
> Draft: Revert "Retry POST after 1 second cooldown when status 429 received"

- differ/differ.go
- differ/differ_test.go
Speedup: don't copy whole `configuration` struct (500 bytes or more) every time
Done on CI
> Speedup: don't copy whole `configuration` struct (500 bytes or more) every time

- deploy/clowdapp.yaml
`activeDeadlineSeconds` and `suspend` can be configured independently for the different Cronjobs 
# Type of change
CI
> Make the different cronjobs' configuration more independent

- differ/cluster_filter.go
- differ/cluster_filter_test.go
- differ/differ.go
Ability to filter clusters by using allow list and block list. All cases are covered by unit tests.
Done on CI.
> Ability to filter clusters by using allow list and block list

- dashboards/grafana-dashboard-ccx-notification-services.configmap.yaml
Update Grafana dashboard to take into account the existing subsystems (notification_backend and service_log).
This new content is exported from the App-SRE [Grafana playground](https://grafana.stage.devshift.net/d/ERzLEqdnk/ccx-notification-services?orgId=1&var-datasource=app-sre-prod-01-prometheus&var-namespace=app-sre-observability-production)
N/A
> Update grafana dashboards to show metrics in each subsystem

- Makefile
- README.md
- differ/cluster_filter_benchmark_test.go
- differ/cluster_filter_test.go
Basic benchmarks for filtering solution
Results seems to be ok-ish so far:
```
BenchmarkNoFiltersNullListOfClustersFiltersDisabled-8           470145574                2.706 ns/op
BenchmarkNoFiltersNullListOfClustersAllowFilterEnabled-8        393646858                3.238 ns/op
BenchmarkNoFiltersNullListOfClustersBlockFilterEnabled-8        372016285                3.314 ns/op
BenchmarkNoFiltersNullListOfClustersFiltersEnabled-8            392002869                3.094 ns/op
BenchmarkNoFiltersEmptyListOfClustersFiltersDisabled-8          448799083                2.717 ns/op
BenchmarkNoFiltersEmptyListOfClustersAllowFilterEnabled-8       370419956                3.116 ns/op
BenchmarkNoFiltersEmptyListOfClustersBlockFilterEnabled-8       352190559                3.842 ns/op …
```
> Basic benchmarks for filtering solution

- dashboards/grafana-dashboard-ccx-notification-services.configmap.yaml
The labels and annotations are not automatically created when the `oc create configmap` command is run. Without these fields, the Grafana dashboard is not found (and therefore not shown).
Will See if dashboard shows in stage
> Add labels and annotations to grafana dashboard

- dashboards/grafana-dashboard-ccx-notification-services.configmap.yaml
With this, the dashbaord now looks like it should when opened:
- The name is changed to `CCX Notification Services`
- The default datasource used is `app-sre-stage-01-prometheus` (since the graph is for stage by default)
- The range of data displayed is `now - 1 hour`
- All the dashboards views show data for service log and notification backend by default
Will see how dashboard is rendered in stage
> Fix datasource, update description, and show not_sent_same_state view by default

- differ/cluster_filter_benchmark_test.go
Benchmarks: finalization
Results:
```
BenchmarkNoFiltersNullListOfClustersFiltersDisabled-8        	404038790	         2.665 ns/op
BenchmarkNoFiltersNullListOfClustersAllowFilterEnabled-8     	392989483	         3.263 ns/op
BenchmarkNoFiltersNullListOfClustersBlockFilterEnabled-8     	349367343	         3.374 ns/op
BenchmarkNoFiltersNullListOfClustersFiltersEnabled-8         	407307870	         3.574 ns/op
BenchmarkNoFiltersEmptyListOfClustersFiltersDisabled-8       	485534881	         2.742 ns/op
BenchmarkNoFiltersEmptyListOfClustersAllowFilterEnabled-8    	363322621	         3.269 ns/op
BenchmarkNoFiltersEmptyListOfClustersBlockFilterEnabled-8    	349120347	         4.002 ns/op
BenchmarkNoFiltersEmptyListOfClustersFiltersEnabled-8        	349924776	         3.542 ns/op …
```
> Benchmarks: finalization

- conf/config.go
- conf/configuration_test.go
- config-devel.toml
- config.toml
- differ/differ.go
- docs/configuration.md
- ocmclient/ocmclient.go
- ocmclient/ocmclient_test.go
- tests/config2.toml
Add optional configuration of token refreshment URL used by OCM client. Right now OCM client uses default one, which is fine, but for BDD tests it would be useful to have a option to configure URL of a mock.
N/A
> Add configuration of token URL in OCMClient

- differ/differ.go
- differ/storage.go
- differ/storage_test.go
Avoid applying the `where` clause if the cooldown is not configured or is set to 0.
updated UTs.
> Refactor read last notified record for cluster list

- differ/differ.go
- differ/differ_test.go
- differ/renderer.go
- differ/renderer_test.go
- types/types.go
`getAllContentFromMap` is currently called every time we want to render the reports for a given cluster, so we are doing this slice creation thousands of times.
Updated UTs
> Call getAllContentFromMap only once

- config-devel.toml
- config.toml
- deploy/clowdapp.yaml
Change endpoint of template renderer to include v1 prefix. Applicable after merge of [this PR](https://github.com/RedHatInsights/insights-content-template-renderer/pull/14).
N/A
> Add v1 prefix to template renderer endpoint

- differ/renderer.go
- differ/renderer_test.go
Service log's description is gathered from the `report.Reason`, not `report.Description`. It's a bit misleading.
Unit tests.
> Add url to reason not description

- differ/comparator.go
Pass `record` by reference. It's size is 121 bytes, reference is 4/8 bytes only.
Done on CI
> Pass `record` by reference

- conf/config.go
- conf/configuration_test.go
- differ/differ.go
Don't pass whole `configuration` to `GetStorageConfiguration function`, use reference instead
Done on CI
> Don't pass whole `configuration` to `GetStorageConfiguration function`, use reference instead

- conf/config.go
- conf/configuration_test.go
- config_benchmark_test.go
- differ/differ.go
- tests/benchmark.toml
Don't pass whole `configuration` to `GetLoggingConfiguration`
Done on CI
> Don't pass whole `configuration` to `GetLoggingConfiguration`

- conf/config.go
- conf/config_benchmark_test.go
- conf/configuration_test.go
- differ/differ.go
- tests/benchmark.toml
Don't pass whole `configuration` to `GetMetricsConfiguration` function
Done on CI
> Don't pass whole `configuration` to `GetMetricsConfiguration` function

- conf/config.go
- conf/config_benchmark_test.go
- conf/configuration_test.go
- differ/differ.go
- tests/benchmark.toml
Don't pass whole `configuration` structure to `GetDependenciesConfiguration` function
Done on CI
> Don't pass whole `configuration` structure to `GetDependenciesConfiguration` function

- conf/config.go
- conf/config_benchmark_test.go
- conf/configuration_test.go
- differ/differ.go
- tests/benchmark.toml
Don't pass whole `configuration` structure to function `GetNotificationsConfiguration`
Done on CI
> Don't pass whole `configuration` structure to function `GetNotificationsConfiguration`

- conf/config.go
- conf/config_benchmark_test.go
- conf/configuration_test.go
- tests/benchmark.toml
Don't pass whole `configuration` structure to function `GetCleanerConfiguration`
N/A
> Don't pass whole `configuration` structure to function `GetCleanerConfiguration`

- differ/differ.go
- producer/kafka/kafka_producer.go
- producer/kafka/kafka_producer_test.go
Don't pass the whole 700 bytes `config` struct to Kafka interface constructor
Done on CI
> Don't pass the whole 700 bytes `config` struct to Kafka interface constructor

- conf/configuration_test.go
Checks if all configuration getters are not mutators
Done on CI
> Checks if all configuration getters are not mutators

- differ/differ_benchmark_test.go
Added benchamark for findRenderedReport in order to measure its performance.
Run benchmarks.
> Add benchmark for findRenderedReport

- differ/differ.go
- differ/renderer.go
- differ/renderer_test.go
Pass configuration by reference info the function `renderReportsForCluster`
Done on CI
> Pass configuration by reference info the function `renderReportsForCluster`

- docs/testing.md
Adding manual e2e test documentation into testing page for GH page.
N/A
> Adding e2e test documentation into testing page

- differ/storage.go
- differ/storage_test.go
If the cooldown is set to 0, we can avoid doing the SELECT query, which we know to be slow due to the filtering.
UTs updated, BDDs
* [] updated documentation wherever necessary
> Do not query previously reported rows if cooldown is set to 0

- differ/storage.go
- differ/storage_test.go
- tests/mocks/Storage.go
Ability to write into `read_error` table
Done on CI
> Ability to write into `read_error` table

- docs/demos/uuid_column_in_db/demo/uuid_column_test.go
`INSERT` benchmarks for various `cluster name` representation
Fixes (partially) INSERT benchmarks for various `cluster name` representation
Can be run from command line (given DB connection string is correct).
> INSERT benchmarks for various cluster name representation

- docs/demos/uuid_column_in_db/demo/uuid_column_test.go
Cluster name column benchmarks 2nd version - `DELETE FROM` benchmarks
Fixes (partially) https://issues.redhat.com/browse/CCXDEV-9915
Can be run from command line if needed.
> Cluster name column benchmarks 2nd version - DELETE FROM benchmarks

- docs/demos/uuid_column_in_db/demo/uuid_column_test.go
- `VARCHAR` variant of benchmarks
- Reorder benchmarks to allow `VARCHAR` variant to be added
- Description of benchmark
Can be run from CI
> UUID column benchmarks: 3rd version

- docs/demos/uuid_column_in_db/demo/uuid_column_test.go
`cluster names` benchmarks: final versions of INSERTion and DELETion benchmarks
- globally configurable `report`
- added docstrings and comments where needed
Can be run from command line.
> `cluster names` benchmarks: final versions of INSERTion and DELETion benchmarks

- docs/demos/uuid_column_in_db/demo/uuid_column_test.go
Benchmarks for indexed `cluster` column name
Can be run from command line.
> Benchmarks for indexed `cluster` column name

- config.toml
- deploy/clowdapp.yaml
- docs/data_flow.md
- [notification-backend] include moderate issues (total risk = 2)
- [config] set cooldown time between notifications to 1 week instead of 24 hours
- [config] update `config.toml` to have same config as `clowdapp.yaml` file
- [documentation] mention maximum cooldown value in docs
With this change, we go from:
- sending ~11k events to ~45k with data similar to what we have in our production database. We can then expect the `reported` table to grow "faster", as each run of the cronjob will add more items than before this change.
- customers that were already receiving notifications might receive more, or bigger ones
- customers that were no receiving notifications might start receiving them if their clusters have unsolved moderate recommendations.
- the biggest execution time impact will be …
> Notify moderate recommendations too with 1 week cooldown

- differ/storage.go
- differ/storage_test.go
- tests/mocks/Storage.go
- Method to check if `read_errors` contains an error for given cluster and given timestamp
- Unit tests covering the whole method (with one exception - closing error, that is IMHO not possible to test using SQL mock)
Done on CI
> Method to check if `read_errors` contains an error for given cluster and given timestamp

- conf/config.go
- config-devel.toml
- config.toml
- deploy/clowdapp.yaml
- differ/differ.go
- docs/configuration.md
- docs/event_targets.md
- producer/servicelog/service_log_producer_test.go
- tests/benchmark.toml
- tests/config2.toml
- tests/config4.toml
- tests/config5.toml
- types/types.go
Send `username` to ServiceLog REST API too
Fixes https://issues.redhat.com/browse/CCXDEV-10004
Done on CI
> Send `username` to ServiceLog REST API too

- differ/differ_test.go
Reformat `differ_test.go` to make linters happy
Fixes https://issues.redhat.com/browse/CCXDEV-10063
Done on CI
> Reformat `differ_test.go` to make linters happy

- differ/storage_test.go
Added missing unit test case for `Storage.ReadLastNotifiedRecordForClusterList` method: empty input sequence
Done on CI
> Added missing unit test case for Storage.ReadLastNotifiedRecordForClusterList: empty input sequence

- differ/storage_test.go
Unit tests for method `Starage.ReadReportForClusterAtOffset`
Fixes https://issues.redhat.com/browse/CCXDEV-10036
Done on CI
> Unit tests for method `Starage.ReadReportForClusterAtOffset`

- differ/storage_test.go
Unit tests for method `Storage.ReadReportForClusterAtTime`
Fixes https://issues.redhat.com/browse/CCXDEV-10035
Done on CI
> Unit tests for method `Storage.ReadReportForClusterAtTime`

- differ/differ.go
- differ/differ_test.go
- producer/kafka/kafka_producer_test.go
- types/types.go
The notification backend version we are depending on does not need the JSON payload to be escaped.
Fixes [CCXDEV-9819](https://issues.redhat.com/browse/CCXDEV-9819)
Updated corresponding UTs, run BDDs locally
> Remove json escaping from notification message

- differ/renderer_test.go
Add `TestRenderReportsForClusterInvalidURL` and `TestRenderReportsForClusterInvalidJSON` covering some missing gaps  in the connection with template renderer.
Unit tests.
> [CCXDEV-10291] Add some unit tests for checking connection errors with template renderer

- differ/differ.go
- differ/differ_test.go
The `notifications_sent` metric is used in the [updateNotificationRecordSentState](https://github.com/RedHatInsights/ccx-notification-service/blob/e7803c5e4cb1d1d030f8962918a3976c7d369b2b/differ/differ.go#L604) which is just used in the [produceEntriesToKafka](https://github.com/RedHatInsights/ccx-notification-service/blob/e7803c5e4cb1d1d030f8962918a3976c7d369b2b/differ/differ.go#L521) function. For the service log, it is updated in the [updateNotificationRecordState](https://github.com/RedHatInsights/ccx-notification-service/blob/e7803c5e4cb1d1d030f8962918a3976c7d369b2b/differ/differ.go#L684), which is executed just at the end of the processing. This creates a a scatter plot rather than a continuous plot, which is impossible to calculate the rate from so we are seeing a metric = 0 in …
> [CCXDEV-10291] Add metrics for service log

- conf/config.go
- conf/configuration_test.go
- config-devel.toml
- config.toml
- differ/differ.go
- differ/metrics.go
- differ/metrics_test.go
- tests/config2.toml
We have a bug in our Grafana dashboards where metrics are constant because they are pushed just at the end of the execution of this job. We need to push the metrics in a loop so that we can see its evolution.
Unit tests.
> [CCXDEV-10291] Push metrics in loop

- differ/comparator.go
- differ/comparator_test.go
- differ/differ.go
- docs/packages/differ/comparator.html
- docs/packages/differ/comparator_test.html
No notifications include specific rule response details. Both ServiceLog and email notifications will look exactly the same regardless of differences in rule response details. So to fix issues were difference in details can make us resend a notification that is still in cool-down, we will base the notification resolution solely on the rule response ID (rule module + response key).
Fixes CCXDEV-10817
CI (existing UTs and BDD tests should pass)
> Remove details equality check from issue comparison

- go.mod
- go.sum
Bump-up Go-SQLmock library to the latest stable version
Will be checked on CI
> Bump-up Go-SQLmock library to the latest stable version

- go.mod
- go.sum
Bump-up `insights-results-types` and `insights-operator-utils` libraries
To be checked on CI
> Bump-up insights-results-types and insights-operator-utils libraries

- differ/comparator.go
- differ/comparator_test.go
- differ/differ.go
- differ/differ_test.go
- differ/renderer.go
- differ/renderer_test.go
- types/types.go
The change itself is about adding the [reportsToRender slice](https://github.com/RedHatInsights/ccx-notification-service/compare/master...epapbak:ccx-notification-service:render_reports_only_when_needed#diff-eb2af045c98f2dc73f17612ac604b9de75162f75e746af09e33783522bfab653R436) , and modifying the [Report structure](https://github.com/RedHatInsights/ccx-notification-service/compare/master...epapbak:ccx-notification-service:render_reports_only_when_needed#diff-f8d2bd35e1a8c9b86c8c4448dde00bc5480652f85ed0630efc012c3906d3a14fR159) so we can handle a slice of pointers.
This is a performance optimization, as we do not have to query the template renderer when not necessary.
Fixes [CCXDEV-11097](https://issues.redhat.com/browse/CCXDEV-11097) partially …
> Render reports only when there are issues to notify

- differ/differ.go
Replacing the `module` field of the reports to render to not call `moduleToRuleName` twice was a really bad idea, as the content template renderer expects the full module name or fails.
Fixes bug introduced in #592
Run service locally with real template renderer and real rules
> Do not replace Module field in reports to render

- differ/differ.go
- types/types.go
Include default severity in created service log entries. The actual severity levels we want to send still need to be decided. The issue is that right now this attribute is needed, when it used to be set by default.
Fixes CCXDEV-12062
- Already tested in UTs (funny, right?)
- BDDs pass
- Stage should be fixed by this change
> Send severity (info) in service log entry

- differ/storage_test.go
Unit test for method `storage.PrintOldReportsForCleanup`
> Unit test for method `storage.PrintOldReportsForCleanup`

- differ/storage.go
Don't close row set twice in `Storage.ReadNotificationType`
Already covered by unit tests
To be re-checked on CI.
> Don't close row set twice in `Storage.ReadNotificationType`

- differ/storage.go
Don't close row set twice in `Storage.ReadStates`
Already covered by unit tests
To be re-checked on CI.
> Don't close row set twice in `Storage.ReadStates`

- differ/comparator.go
- differ/comparator_test.go
- differ/differ.go
- differ/differ_test.go
- differ/evaluator_test.go
- differ/export_test.go
- differ/metrics.go
- differ/metrics_test.go
- differ/renderer_test.go
- docs/event_targets.md
- types/types.go
- Introduce `EvaluatedReportItem` structure to hold the `ReportItem` with additional metadata (calculated total risk, so far)
- Set the severity in the created service log event depending on the calculated total risk. The severity is set to the corresponding critical risk when possible, or to "Info" if we somehow handle an unexpected total risk value.
- Added service-log related UTs
Fixes CCXDEV-11831
CI
> [CCXDEV-11831] Set service log severity based on calculated total risk

- differ/storage_test.go
Unit tests for `storage.WriteNotificationRecordForCluster`
Fixes #533 
> Unit tests for `storage.WriteNotificationRecordForCluster`

- differ/differ.go
- differ/differ_test.go
whole method except for `os.Exit()` block is now covered
https://issues.redhat.com/browse/CCXDEV-10739
`make test`
> add UT coverage for (d *Differ) SetupFiltersAndThresholds

- docs/event_targets.md
Update documentation to specify what endpoint of the OCM Service Log API is used by our service.
N/A
> Update event target documentation with used service log endpoint

- differ/differ.go
- differ/metrics.go
- differ/metrics_test.go
When metrics are not configured or the authentication token for the push gateway is not set, do not try to push the metrics.
Fixes CCXDEV-12409
- Updated corresponding UTs
- CI
> Do not try to push metrics if namespace or auth token are not set

- deploy/clowdapp.yaml
This secret is not set in all the environments we use. Since the service is now prepared to work without `CCX_NOTIFICATION_SERVICE__METRICS__GATEWAY_AUTH_TOKEN` env var, let's mark it as optional so the deployment doesn't fail when the secret does not exist.
Fixes CCXDEV-11428
CI
> Make push-gateway-basic-auth secret optional

- cmd/ccx-notification-service/cli.go
- conf/config.go
- conf/config_benchmark_test.go
- conf/configuration_test.go
- deploy/clowdapp.yaml
- differ/differ_test.go
- differ/errors.go
- docs/configuration.md
- producer/kafka/kafka_producer.go
- producer/kafka/kafka_producer_test.go
- tests/benchmark.toml
- tests/config1.toml
- tests/config2.toml
- tests/config4.toml
- tests/config5.toml
This is the simplest change required to support multiple broker addresses (without refactoring common code out of the service and so on).
Now the configuration of the Kafka Broker expects the field `addresses` instead of `address`, and said field is a comma-separated list of broker addresses. For example: `kafka:9092,kafka:9093,localhost:29092`. The list does not have a minimum or maximum number of addresses, so it can be used as before with only one address: `kafka:29092`.
Fixes CCXDEV-12461
- UTs
- BDDs
> Support for multiple broker addresses

- .github/workflows/bdd.yaml
- .github/workflows/gh-pages.yml
- .github/workflows/gotests.yaml
- .github/workflows/linters.yaml
- Dockerfile
- build.sh
- go.mod
> Update go version to 1.20

- Dockerfile
Our builder for ccx-notification-service fails with
```
#10 0.222 fatal: detected dubious ownership in repository at '/opt/app-root/src'
#10 0.222 To add an exception for this directory, call:
#10 0.222
#10 0.222 git config --global --add safe.directory /opt/app-root/src
```
CI
> [CCXDEV-12685] Update Dockerfile fixing builder

- .github/workflows/linters.yaml
Splitting linters job in CI to separate steps
Fixes [CCXDEV-12634](https://issues.redhat.com/browse/CCXDEV-12634)
> [CCXDEV-12634] Splitting linters into separate steps

- deploy/clowdapp.yaml
The URL env variable was set as optional in clowdapp, but auth secret is not. Making it optional makes the service runnable in ephemeral environment.
NA
> Make push gateway auth secret optional

- deploy/clowdapp.yaml
push-gateway-secret is not present in ephemeral environment, so this PR makes it optional. 
NA
> [CCXDEV-9710] Make push-gateway-secret optional for service log

- cmd/ccx-notification-service/main.go
- config.toml
- deploy/clowdapp.yaml
- differ/differ.go
Adding configuration for notification service to be able to send error mesages to GlitchTip.
Fixes # [CCXDEV-10823](https://issues.redhat.com/browse/CCXDEV-10823)
Tested locally with config.toml file and also by exporting the env var
> [CCXDEV-10823] Adding Glitchtip confiuration to notification service

- differ/differ.go
- differ/storage.go
- differ/storage_test.go
- tests/mocks/Storage.go
- Reduce the number of errors generated when handling the `read_errors` table by handling errors better
- Refactor a little bit the naming used in the function's arguments
Fixes CCXDEV-12913
- Added UTs -> CI
- Stage -> I want to see if the error message stops being produced with our current testing data
> Handle read_errors table operations more gracefully

- Dockerfile
Use image from registry.access.redhat.com for Konflux build
Needed for CCXDEV-14124
CI
> [CCXDEV-14124] Get builder image from registry.access.redhat.com for Konflux

- .github/workflows/bdd.yaml
- .github/workflows/gotests.yaml
- .github/workflows/linters.yaml
- .github/workflows/shellcheck.yaml
- gocyclo.sh
- pr_check.sh
Update CI to use most recent Go versions, as the base image used for building the ccx-notification-service is already using Go 1.22.
Updated runner image to ubuntu-24.04 because 20.04 is already deprecated.
CI configuration update, to be checked on CI.
> Update Go version and runner image
