RedHatInsights/ccx-notification-service

ccx_notification_service.go
go.mod

Logger initialization

---

PoC-differ/content.go
PoC-differ/differ.go
PoC-differ/types.go

Impacts read from global config file

Impacts read from global config file

---

PoC-differ/differ.go

Differ part

---

conf/config.go
conf/configuration_test.go
config.toml
go.mod
tests/config1.toml
tests/config2.toml

This changes extracts configuration in its own package, so it can be used in other packages aside from the differ.
UTs

Adding configuration module

---

.travis.yml
Makefile
unit-tests.sh

Unit tests environment
Will be done on CI soon!

Unit tests environment

---

CODEOWNERS
go.mod
producer/producer.go
producer/producer_test.go

Add CODEOWNERS file as in other ccx repositories

Add CODEOWNERS file

---

.travis.yml
PoC-differ/content.go
PoC-differ/differ.go
PoC-differ/storage.go
goconst.sh

Removed duplicated constants
Done on CI automagically

Removed duplicated constants

---

.travis.yml
PoC-differ/differ.go

- Reduce cyclomatic complexity
- Enable rest of checkers on CI
Done on CI

Reduce cyclomatic complexity + enable rest of checkers on CI

---

PoC-differ/content.go
PoC-differ/differ.go
PoC-differ/storage.go
producer/producer.go
producer/producer_test.go
types/types.go

Refactor types out of differ package so they can be reused in other packages.
CI

Add types package and update references

---

.gitignore

Ignore result binary

---

PoC-differ/go.mod

Bump-up Go version

---

PoC-differ/config.toml
PoC-differ/differ.go
PoC-differ/storage.go
conf/config.go
go.sum
types/types.go

Send weekly notification with the actual content expected by the email template.
Manual production of notification messages.

Weekly notification content update

---

unit-tests.sh

Verbose mode for unit tests
Done on CI

Verbose mode for unit tests

---

PoC-differ/storage.go
types/types.go

Updated ClusterReport

---

PoC-differ/storage.go
types/types.go

Ability to read notification types
N/A

Ability to read notification types

---

PoC-differ/storage.go
types/types.go

Ability to read notification states
N/A

Ability to read notification states

---

PoC-differ/storage.go

Select report by timestamp or offset
N/A

Select report by timestamp or offset

---

PoC-differ/content.go
PoC-differ/differ.go
PoC-differ/storage.go
types/types.go

Small fixes
Compiling the code and running go test

Fix int to string conversion and some message formatting directives

---

conf/config.go
go.mod
go.sum

Clowder config stub

---

PoC-differ/differ.go
PoC-differ/differ_test.go
PoC-differ/go.mod
PoC-differ/go.sum

Add some UT coverage for differ to simplify next steps + some refactoring
Fixes #23 
UTs run correctly

Add differ UTs

---

differ/storage.go

Ability to write notification status
N/A

Ability to write notification status

---

differ/differ.go

Total risk threshold as constant
N/A

Total risk threshold as constant

---

differ/storage.go
types/types.go

Better notification record storage
N/A

Better notification record storage

---

differ/storage.go

Read latest report only from `new_reports` table.
N/A

Read latest report only

---

README.md

Makefile targets in README.md
N/A

Makefile targets in README.md

---

README.md

Add all badges into README.md
N/A

Add all badges into README.md

---

PoC-updater/types/types.go
PoC-updater/updater.go

Ability to notify about new issues only
Fixes #56 
N/A

Ability to notify about new issues only

---

Dockerfile
build_deploy.sh
pr_check.sh

Add image building

---

conf/configuration_test.go

Config tests should not be in `main` package
N/A

Config tests should not be in main package

---

conf/configuration_test.go
tests/config3.toml

Clowder config tests

---

differ/differ.go

Once deployed, this service would be hindered by this function.
Launched the service

Remove waitForEnter function (demo only functionality)

---

conf/config.go
conf/configuration_test.go

Proper handling of environment variables.
Fixes #77
N/A

Fix issue #77

---

conf/config.go
conf/configuration_test.go

Fix configuration key for content server

---

docs/index.md
docs/packages/conf/config.html
docs/packages/conf/configuration_test.html
docs/packages/differ/differ.html

Link to godoc

---

PoC-updater/storage.go
differ/storage.go
docs/packages/PoC-updater/storage.html
docs/packages/PoC-updater/updater.html
docs/packages/differ/storage.html

Printable SQL statements in logs
N/A

Printable SQL statements in logs

---

PoC-updater/storage.go
docs/packages/PoC-updater/storage.html

Sync PoC with real code

---

PoC-updater/storage.go
differ/storage.go
docs/packages/differ/storage.html

Delete row from `new_reports` table
Fixes #55
N/A

Delete row from `new_reports` table

---

PoC-updater/storage.go
differ/storage.go
docs/packages/PoC-updater/storage.html
docs/packages/PoC-updater/updater.html
docs/packages/differ/storage.html
tests/mocks/Storage.go

Ability to delete specified row in `results` table
Fixes #62
N/A

Ability to delete specified row in `results` table

---

go.mod

Updated go.mod

---

docs/index.md

Data flow description
Fixes #64
N/A

Data flow description

---

docs/index.md

Fixed grammar + remarks about architecture
N/A

Fixed grammar + remarks about architecture

---

ccx_notification_service.go
differ/comparator.go
differ/differ.go
differ/differ_test.go
producer/kafka_producer.go

Cleaning up not useful logs
CI

Logging improvement

---

conf/configuration_test.go
config.toml
tests/config2.toml

That missing 's' changes everything.
Added corresponding tests

Correct config for notification context and urls settings

---

docs/local_setup.md

Fix typo in Jekyll nav page order.

Fix local setup nav number

---

differ/differ.go
differ/differ_test.go
types/types.go

Use better types

---

differ/differ.go
differ/differ_test.go
types/types.go

Even better types
N/A, done on CI hopefully

Even better types

---

README.md

Added service description and usage to README.md file
Fixes #118 
N/A

Add service description and usage in README file

---

conf/config.go
differ/comparator.go
differ/differ.go
differ/metrics.go
differ/metrics_test.go
go.mod

Add some basic counters for the notification service
Added basic UT + CI

Adding instant report metrics

---

differ/differ.go

Quick refactor of metrics setup
- Refactor
CI

Refactor metrics setup in differ

---

differ/differ.go

Naming refactor and moving some code around
CI

Refactor setupMetrics into startMetricsServer

---

README.md
conf/config.go
differ/differ.go

Command line option to display actual configuration
Fixes #128 
N/A

Command line option to display actual configuration

---

differ/metrics.go

It says it pushes, but there's nothing on the other side, so... 
N/A

Add debug info to PushGatewayClient::Do method

---

differ/differ.go
differ/storage.go

`Replace` to `ReplaceAll`

---

differ/content.go
differ/differ.go
differ/differ_test.go
go.mod
go.sum
types/types.go

Reverts RedHatInsights/ccx-notification-service#144, as the corresponding changes in other services have been reverted

Revert "change impact type"

---

conf/config.go
differ/comparator.go
differ/differ.go
differ/differ_test.go
differ/storage.go
tests/mocks/Storage.go

Minor improvements of code base
Done on CI

Minor improvements of code base

---

bdd_tests/features/steps/database.py
bdd_tests/features/steps/dependencies.py
bdd_tests/features/steps/notification_service.py

Python has Unicode strings by default
N/A

Python has Unicode strings by default

---

bdd_tests/config.toml
bdd_tests/features/customer_notifications.feature
bdd_tests/features/steps/database.py
conf/config.go
config-devel.toml
config.toml
differ/comparator.go
differ/differ.go

Allow to resend a notification for the same issue after a given cool down time has elapsed.
- Behavioral tests (no changes in the code)
New tests added (UTs and BDD)

Notification cooldown mechanism

---

differ/comparator.go

Wrong timestamp used in comparison.
local runs + CI

Fix notification cooldown comparison

---

differ/comparator.go

Improve logging to see what happens in stage/prod when the timestamps are compared.
N/A

Improve logs of notification cooldown comparison

---

gosec.sh

Bump-up `gosec` to the latest version
Fixes #161
Done on CI

Bump-up `gosec` to the latest version

---

conf/configuration_test.go
gosec.sh

Minor removed commented code
N/A

Minor removed commented code

---

differ/content.go

Don't use deprecated function
Done on CI

Don't use deprecated function

---

deploy/ccx-notification-service.yaml

Moving saas templates directly to service repo since the saas-templates repo will be archived.

[CCXDEV-7159] Add saas-templates

---

Makefile
bdd_tests/mocks/insights-content-service/content_server.py
bdd_tests/mocks/prometheus/push_gateway.py
bdd_tests/run_tests.sh
dashboards/grafana-dashboard-ccx-notification-service.configmap.yaml
deploy/ccx-notification-service.yaml

Add license

---

.github/workflows/golangci-lint.yml
conf/configuration_test.go
differ/metrics.go
producer/producer_test.go

GH action setup

---

.github/workflows/golangci-lint.yml
differ/comparator.go
differ/comparator_test.go

Enable all tests on CI
Done on CI hopefully

Enable all tests

---

deploy/clowdapp.yaml

Add clowder.yaml file for stage/prod deployment using clowder.

[CCXDEV-5982] Add clowdapp.yaml file

---

conf/config.go
deploy/clowdapp.yaml

Incude suppot for parsing the Clowder file

Adding support for clowder and update the config file

---

deploy/clowdapp.yaml

[CCXDEV-7742] Fix clowdapp.yml syntax

---

deploy/clowdapp.yaml

Revert clowdapp.yaml syntax fix

---

deploy/clowdapp.yaml

Drop deployment dependency on ccx-notification-writer

[CCXDEV-7742] Reference directly ccx-notification-db

---

build_deploy.sh
deploy/clowdapp.yaml

Renames the clowdapp deployment name and use for quay.io tag latest.

[CCXDEV-7742] fix clowdapp deployment names

---

deploy/clowdapp.yaml

Fix access to ccx-notification-db by leveraging ccx-notification-writer db setup.

[CCXDEV-7742] fix access to db

---

README.md
conf/config.go
deploy/clowdapp.yaml
pr_check.sh

Testing ephemeral env. for running integration tests.

[CCXDEV-6171] testing running integration tests in ephemeral env

---

docs/demos/dsl-events-filtering/evaluator.go
docs/demos/dsl-events-filtering/events_filter.go
docs/demos/dsl-events-filtering/go.mod
docs/demos/dsl-events-filtering/run.sh
docs/demos/dsl-events-filtering/shunting_yard.go
docs/demos/dsl-events-filtering/stack.go
docs/demos/dsl-events-filtering/token.go

Events filter demo

---

docs/demos/dsl-events-filtering/events_filter.md

Event filter: slides

---

bdd_tests/config.toml
conf/config.go
config-devel.toml
config.toml
deploy/clowdapp.yaml
differ/differ.go
differ/differ_test.go
producer/kafka_producer.go
producer/producer_test.go
tests/config2.toml

Kafka target enable/disable
Done on CI I hope :)

Kafka target enable/disable

---

conf/config.go
config-devel.toml
config.toml
differ/differ.go
tests/config2.toml

Make total risk threshold configurable
dependencies that are required for this change.
Fixes #201
Done on CI

Make total risk threshold configurable

---

conf/config.go
conf/configuration_test.go
config-devel.toml
config.toml
differ/differ.go
tests/config2.toml

Service log basic config
Done on CI

Service log basic config

---

conf/config.go
config-devel.toml
config.toml
differ/differ.go
differ/differ_test.go
tests/config2.toml

Event filter
Fixes #202 
Fixes #203 
Fixes #204 
Done on CI

Event filter

---

deploy/clowdapp.yaml

Update clowdapp.yaml with TOTAL_RISK_THRESHOLD.
This is in order to stop sending tons of emails.
None.

Update clowdapp.yaml with TOTAL_RISK_THRESHOLD

---

deploy/clowdapp.yaml

Filter expression in Clowdapp config
See stage logs

Filter expression in Clowdapp config

---

conf/config.go
config-devel.toml
config.toml
deploy/clowdapp.yaml
differ/differ.go
tests/config2.toml

Other thresholds made configurable
Fixes #202 
Fixes #203 
Fixes #204 
Elementary tests done on CI.

Other thresholds made configurable

---

differ/differ.go
types/types.go

Verbose logs

---

deploy/clowdapp.yaml

Fixed filter setup
N/A!!! we need to wait for Stage

Fixed filter setup

---

conf/configuration_test.go

Unit test for `GetCleanerConfiguration` function
Done on CI

Unit test for GetCleanerConfiguration function

---

differ/comparator_test.go

Use new octal literal
Done on CI

Use new octal literal

---

docs/demos/dsl-events-filtering/events_filter.md

Updated presentation (demo)
N/A

Updated presentation (demo)

---

README.md

Updated README a bit

---

differ/storage.go
tests/mocks/Storage.go

add event_type_id column
Fixes CCXDEV-8774
- n/a

add event_type_id column

---

Makefile
README.md

Missing help in README.md

---

differ/storage.go

get only the necessary columns
Fixes CCXDEV-8770
- 
- n/a

get only the necessary columns

---

.gitignore
Makefile
README.md
profile.sh

Ability to run profiler

---

profile.sh

Profile generation

---

differ/differ.go

Better reporting

---

docs/demos/shrinking_report_table/shringink_report_table.md

Shrinking report table report - 1st version
N/A

Shrinking report table report - 1st version

---

differ/storage.go

Log the ReadLastNotifiedRecordForClusterList query as we are suffering some issue in stage.
- Debugging
None

[CCXDEV-8782] Log the ReadLastNotifiedRecordForClusterList query

---

docs/demos/shrinking_report_table/shringink_report_table.md

Shrinking report table report - 2nd version
N/A

Shrinking report table report - 2nd version

---

docs/demos/shrinking_report_table/shringink_report_table.md

Shrinking report table report - 3rd version
N/A

Shrinking report table report - 3rd version

---

Makefile

Run `gen-mocks` before `test`. This way, when we run `make before_commit` we make sure the mocks are updated. We forgot to do it before.
Locally run it.

[CCXDEV-8782] Generate the mocks before testing

---

deploy/clowdapp.yaml

Add a new cronjob for service log.
Have to be merged with https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/46364.
None yet.

[CCXDEV-8785] Deploy service log

---

deploy/clowdapp.yaml

Fix typo. Kafka wasn't disabled because the env variable was wrong.
Locally.

[CCXDEV-8785] Fix typo

---

docs/index.md

Document the notification cooldown mechanism

Update documentation related with notification cooldown

---

README.md
docs/_config.yml
docs/architecture.md
docs/configuration.md
docs/database.md
docs/index.md

Documentation refactoring phase #1
N/A

Documentation refactoring phase #1

---

docs/data_flow.md
docs/index.md

Moved cooldown mechanism

---

docs/configuration.md

Documentation for configuration relevant to Service Log
N/A

Add configuration documentation for Service Log integration

---

PoC-updater/storage.go
differ/storage.go
tests/mocks/Storage.go

Removed unused code: cleanup new reports for org
Done on CI

Removed unused code: cleanup new reports for org

---

PoC-updater/storage.go
ccx_notification_service.go
differ/storage.go
tests/mocks/Storage.go

Removed unused code cleanup old reports for org
Done on CI

Removed unused code cleanup old reports for org

---

docs/ci.md
docs/clowder.md
docs/database.md
docs/event_targets.md
docs/local_setup.md
docs/notification_templates.md

Adding Clowder configuration section to docs
No testing

Adding clowder configuration stuff

---

differ/differ.go

`startDiffer` function in `differ/differ.go` is large and with Service Log integration, it will become even more complex. Introduced changes decrease the size of this function at least a little bit. The behavior of handling of errors during storage/producer closure has been also changed (so that failure of one does not prevent closing other things). 
N/A

Refactor startDiffer function in differ/differ.go

---

conf/config.go
conf/configuration_test.go
differ/differ.go
producer/disabled/disabled_producer.go

Style fixes

---

deploy/clowdapp.yaml

The cleanup will be done in a separate cronjob from now on
N/A

Disable database cleaning on startup

---

differ/differ.go

Add initialization and closure of the `serviceLogNotifier` to `startDiffer` function.
N/A

Add setup and cleanup of service log notifier

---

Makefile
README.md

Ability to build binary with tests
N/A

Ability to build binary with tests

---

differ/differ.go

Declaration and initialization of filters and thresholds for sending notifications to Service Log.
N/A

Add service log filters and thresholds

---

docs/demos/shrinking_report_table/demo/gzip.go

Fix gosec-related error in demo
Done on CI

Fix gosec-related error in demo

---

differ/differ.go

I forgot to print the subsystem as part of the configuration in CLI.
Compile and run.

print metrics subsystem as part of the configuration

---

dashboards/grafana-dashboard-ccx-notification-service.configmap.yaml

Start using the new metrics. F.e: [ccx_notification_service_deserialize_report_errors](https://prometheus.app-sre-stage-01.devshift.net/graph?g0.expr=ccx_notification_service_deserialize_report_errors&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=2h) is now [ccx_notification_service_notification_backend_deserialize_report_errors](https://prometheus.app-sre-stage-01.devshift.net/graph?g0.expr=ccx_notification_service_notification_backend_deserialize_report_errors&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=2h)
Manually in UI.

[CCXDEV-9219] Update dashboard

---

deploy/clowdapp.yaml

Enables sending notifications to Service Log.
N/A

Enable sending notifications to Service Log

---

differ/differ.go
ocmclient/ocmclient.go
producer/servicelog/service_log_producer.go

Additional logs for easier debugging of stage/prod issues
N/A

Extra logs when service log starts

---

differ/differ.go
producer/servicelog/service_log_producer.go

Notification event urls struct

---

differ/differ.go

Check if the SL producer should notify (message was already sent).
None.

[Service Log] check if should notify

---

CODEOWNERS

Added Juan

---

differ/differ.go

Add logging for easier debugging in stage and prod.
None.

[Service Log] add logging

---

differ/differ.go

Don't shadow package name
Done on CI

Don't shadow package name

---

differ/export_test.go
differ/renderer.go
differ/renderer_test.go

More efficient map to slice conversion
Done on CI

More efficient map to slice conversion

---

differ/renderer.go
differ/renderer_test.go

Zero local copy of struct
Done on CI

Zero local copy of struct

---

differ/differ.go

Just doing the same thing we are doing with kafka.
Unit tests.

[Service Log] count number of messages sent

---

docs/demos/dsl-events-filtering/shunting_yard.go
gocyclo.sh

Reduce cyclomatic complexity threshold
- Other
Done on CI

Reduce cyclomatic complexity threshold

---

ocmclient/ocmclient.go

Named multiple return values
Done on CI

Named multiple return values

---

differ/comparator.go
differ/comparator_test.go
differ/content.go
differ/differ.go
differ/differ_cli_args_test.go
differ/differ_test.go
differ/metrics.go
differ/metrics_test.go
differ/renderer.go
differ/renderer_test.go
differ/storage.go
differ/storage_test.go

Fixed import order:
1) standard packages
2) packages from other vendors
3) our packages
Done on CI

Fixed import order

---

ocmclient/ocmclient.go

Shorter function header
Done on CI

Shorter function header

---

deploy/clowdapp.yaml

Have different parameters for the cooldown environment variable depending on the destination, since the two jobs do not send the events in a similar fashion.
N/A

Separate cooldown env var

---

conf/config.go

Even `updateConfigFromClowder` does not return any error
Done on CI

Even `updateConfigFromClowder` does not return any error

---

differ/differ.go

Fix retrieval of previously reported issues. Right now only issues reported for one event target type are being retrieved.
local testing

Retrieve previously reported with target

---

conf/configuration_test.go
tests/config4.toml

Unit tests for config loader
Done on CI

Unit tests for config loader

---

docs/references.md

Template renderer in references
N/A

Template renderer in references

---

docs/data_flow.md

Template renderer in data flow
N/A

Template renderer in data flow

---

differ/comparator.go

Refactor: replace `if-elseif` chain with `switch`
Done on CI

Refactor: replace `if-elseif` chain with `switch`

---

differ/differ.go

Print client ID on startup
Done on CI

Print client ID on startup

---

conf/config.go
conf/configuration_test.go
config-devel.toml
config.toml
differ/differ.go
docs/configuration.md
tests/config1.toml
tests/config4.toml
tests/config5.toml

Ability to specify cluster allowlist in configuration file and in environment variables too (if needed).
Done on CI

Ability to specify cluster allowlist

---

conf/config.go
conf/configuration_test.go
config-devel.toml
config.toml
docs/configuration.md
tests/config1.toml
tests/config2.toml
tests/config4.toml
tests/config5.toml

Ability to specify cluster blocklist
Done on CI

Ability to specify cluster blocklist

---

differ/cluster_filter_benchmark_test.go

More benchmarks for cluster filter
N/A

More benchmarks for cluster filter

---

dashboards/grafana-dashboard-ccx-notification-service.configmap.yaml
dashboards/grafana-dashboard-ccx-notification-services.configmap.yaml

Stage dashboard is not working properly with the JSON exported from the playground. We will update it manually instead.
N/A

Revert changes with Grafana dashboards updates

---

.gitignore
docs/benchmarks.md

Doc benchmarks
Documentation about benchmarks.

Doc benchmarks

---

docs/benchmarks.md
docs/ci.md
docs/database.md
docs/documentation_for_developers.md
docs/local_setup.md
docs/references.md
docs/source_files.md
docs/template_renderer.md
docs/testing.md

Information about template renderer
Fixes #[CCXDEV-9378](https://issues.redhat.com/browse/CCXDEV-9378)
N/A

Information about template renderer

---

check_coverage.sh

Re-enable check coverage
Done on CI

Re-enable check coverage

---

docs/template_renderer.md

Update documentation to match serve log entry current content.
N/A

Swap summary and description content in documentation

---

conf/config.go
conf/configuration_test.go
config-devel.toml
config.toml
docs/configuration.md
tests/config2.toml
tests/config4.toml
tests/config5.toml

New configuration option: URL to detailed info about recommendation
Done on CI

New configuration option: URL to detailed info about recommendation

---

docs/data_flow.md

The expected format of the `cooldown` configuration option was not documented
N/A

Update cooldown docs to specify expected format

---

docs/event_targets.md

Add section to `event_targets.md` about contents of JSON sent to Service Log.
N/A

Add section to docs describing contents for service log entry

---

differ/storage.go

Better test for empty string
Done on CI

Better test for empty string

---

differ/storage_test.go
ocmclient/ocmclient.go

Combine parameters in function headers
Done on CI

Combine parameters in function headers

---

differ/differ.go
docs/configuration.md

Log level settings
Fixes #CCXDEV-9561
Done on CI

Log level settings

---

differ/differ.go
differ/renderer.go

Debug logging for template renderer 
Done on CI

Debug logging for template renderer 

---

.editorconfig

Dot editorconfig

---

differ/differ.go
differ/differ_test.go

Add dependencies configuration logging and modify test accordingly.
N/A

Add dependencies configuration logging

---

deploy/clowdapp.yaml

Convert log level into parameter

Convert log level into parameter

---

deploy/clowdapp.yaml

Forgot to update it here. See https://github.com/RedHatInsights/ccx-notification-service/pull/384.

Convert log level into parameter for service log too

---

deploy/clowdapp.yaml

The variable didn't match the config name.

Fix env variable

---

PULL_REQUEST_TEMPLATE.md

"Configuration update" option in pull request template
- Other
N/A

"Configuration update" option in pull request template

---

docs/data_flow.md

Cool down typos fix

---

docs/clowder.md
docs/configuration.md

Minor grammar fixes
Done on CI

Minor grammar fixes

---

conf/config_benchmark_test.go
config_benchmark_test.go

Benchmark for `conf.GetStorageConfiguration`
Done on CI

Benchmark for `conf.GetStorageConfiguration`

---

conf/config.go
conf/config_benchmark_test.go
conf/configuration_test.go
differ/differ.go
differ/differ_test.go
producer/kafka/kafka_producer.go

Refactoring: pass configuration by reference + benchmark for `GetKafkaBroker` configuration
Done on CI

Refactoring: pass configuration by reference + benchmark for `GetKafkaBroker` configuration

---

conf/config.go
conf/config_benchmark_test.go
conf/configuration_test.go
differ/differ.go
producer/servicelog/service_log_producer_test.go
tests/benchmark.toml

Benchmark for `GetServiceLogConfiguration` + refactoring to pass configuration by reference
Done on CI

Benchmark for `GetServiceLogConfiguration` + refactoring to pass configuration by reference

---

deploy/clowdapp.yaml

Increment the number of pods kept after completion both in case of success or failure.
Not tested!
* [] `make before_commit` passes

Augment number of pods kept after completion

---

config.toml

Change the issue threshold to send notification
Fixes n/a
- n/a

change threshold

---

deploy/clowdapp.yaml

- Revert #400
- Set `total_risk` threshold value to 0, so all issues are notified in the `notification_service_to_service_log` cronjob.
N/A

Set service log total risk threshold to 0

---

.travis.yml

Run shellcheck on CI
Done on CI

Run shellcheck on CI

---

differ/differ_test.go
differ/export_test.go

Unit test for function `convertLogLevel`
Done on CI

Unit test for function `convertLogLevel`

---

differ/differ.go
differ/differ_test.go

Further optimizations
Done on CI

Further optimizations

---

conf/config.go
conf/configuration_test.go
types/types.go

Tags set for better performance
Done on CI

Tags set for better performance

---

differ/differ.go

Filter by tags: preparation steps
Done on CI

Filter by tags: preparation steps

---

docs/configuration.md

Fixed typo

---

docs/configuration.md

Kafka broker configuration docs
N/A

Kafka broker configuration docs

---

Makefile
README.md

Makefile target to generate function list from service executable
N/A

Makefile target to generate function list from service executable

---

Makefile
README.md

Updated Makefile help for target build + missing line
N/A

Updated Makefile help for target build + missing line

---

conf/config.go
differ/differ.go
types/types.go
types/types_test.go

Implementing the tags filtering.
Regular local testing

Implement tags filtering

---

deploy/clowdapp.yaml

Added configuration change for the service log notifications, adding the right tags filtering
Tested locally

Add service log configuration parameters

---

.github/workflows/golangci-lint.yml

Fixed golang CI

---

docs/data_flow.md
docs/event_targets.md

Doc update about the version field included in the event sent to the notification backend.
N/A

Update documentation about notification event version

---

deploy/clowdapp.yaml

Fix typo in successfulJobsHistoryLimit definition

---

docs/demos/uuid_column_in_db/demo/run_benchmark.sh
docs/demos/uuid_column_in_db/demo/uuid_column_test.go

UUID column benchmarks: stub + first crude benchmark
- Demo/PoC
Can be run locally by using script `run_benchmark.sh`

UUID column benchmarks: stub + first crude benchmark

---

differ/differ.go

Trivial fix: parameter combine
Fixes N/A
N/A

Trivial fix: parameter combine

---

conf/configuration_test.go

Proper format for `configuration_test.go`
Fixes https://issues.redhat.com/browse/CCXDEV-9938
N/A

Proper format for configuration_test.go

---

docs/demos/uuid_column_in_db/demo/uuid_column_test.go

SELECTion benchmarks
Fixes https://issues.redhat.com/browse/CCXDEV-9915
Can be run from command line.

SELECTion benchmarks

---

differ/differ_benchmark_test.go

Reformatted differ benchmark
Fixes https://issues.redhat.com/browse/CCXDEV-9951
N/A

Reformatted differ benchmark

---

docs/demos/uuid_column_in_db/demo/run_benchmark.sh
docs/demos/uuid_column_in_db/demo/uuid_column_test.go

Benchmarks: final fixes
Can be run from CLI

Benchmarks: final fixes

---

conf/config.go
config-devel.toml
config.toml
deploy/clowdapp.yaml
differ/differ.go
docs/configuration.md
tests/benchmark.toml
tests/config2.toml
tests/config4.toml
tests/config5.toml

New configuration option: `created_by`
- This change requires a documentation update
N/A

New configuration option: `created_by`

---

deploy/clowdapp.yaml

Set total risk threshold to 2 to include moderate issues
Fixes CCXDEV-9817
N/A

Set total risk threshold to 2 to include moderate issues

---

producer/servicelog/service_log_producer_test.go

Real *ServiceLog* producer unit test that check the actual behaviour - what is send
Done on CI

Real ServiceLog producer unit test

---

docs/demos/uuid_column_in_db/cluster_names.md

Slides: new benchmarks

---

differ/differ.go

Skip already reported errors
Fixes https://issues.redhat.com/browse/CCXDEV-9499
Done on CI

Skip already reported errors

---

docs/event_targets.md

Fixed typo in event targets documentation
N/A

Fixed typo in event targets documentation

---

docs/demos/uuid_column_in_db/cluster_names.md

Cluster name as UUID: final version of slides
Fixes https://issues.redhat.com/browse/CCXDEV-10024
N/A

Cluster name as UUID: final version of slides

---

differ/storage_test.go

Unit tests for `storage.ReadStates` method.
Fixes https://issues.redhat.com/browse/CCXDEV-10033
Done on CI.

Unit tests for storage.ReadStates method

---

types/types_test.go

Fixed issue CCXDEV-10077
Fixes https://issues.redhat.com/browse/CCXDEV-10077
Done on CI

Fixed issue CCXDEV-10077

---

differ/storage_test.go

Unit tests for method `Storage.ReadClustersList`
Fixes https://issues.redhat.com/browse/CCXDEV-10034
Done on CI

Unit tests for method Storage.ReadClustersList

---

docs/demos/uuid_column_in_db/results/plot_results.py
tools/instant_reports.py
tools/sequence_diagram.py
tools/weekly_reports.py

Reformatted all Python sources
N/A

Reformatted all Python sources

---

differ/storage_test.go

Unit tests for method `Storage.ReadReportForCluster`
Fixes https://issues.redhat.com/browse/CCXDEV-10037
Done on CI

Unit tests for method `Storage.ReadReportForCluster`

---

differ/storage.go

Refactoring: more readable queries
Done on CI

Refactoring: more readable queries

---

docs/demos/uuid_column_in_db/demo/uuid_column_test.go

Fixed spelling errors in demos
N/A

Fixed spelling errors in demos

---

differ/differ.go

Simple refactoring: param type combine in `differ.go`
Done on CI

Simple refactoring: param type combine in `differ.go`

---

docs/demos/uuid_column_in_db/demo/uuid_column_test.go

Param type combine in UUID benchmark
N/A

Param type combine in UUID benchmark

---

generate_db_schema_doc.sh

Updated DB description generator
N/A

Updated DB description generator

---

differ/storage.go

Bad syntax due to forgotten quote in the SELECT statements

Fix SQL select error due to bad syntax

---

conf/config.go
differ/differ.go
ocmclient/ocmclient.go
producer/disabled/disabled_producer.go
producer/kafka/kafka_producer.go
producer/producer.go
producer/servicelog/service_log_producer.go
tests/mocks/mocks.go
types/types.go

Package level documentation strings - to fill-in all blank areas there https://pkg.go.dev/github.com/RedHatInsights/ccx-notification-service#section-directories
N/A

Package level documentation strings

---

PoC-updater/updater.go
conf/config.go
config-devel.toml
config.toml
deploy/clowdapp.yaml
differ/differ.go
differ/differ_test.go
go.mod
go.sum

added cloudwatch in order to have logs into kibana
Fixes CCXDEV-9161
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.

added cloudwatch features

---

config-devel.toml
config.toml

remove duplicated table in config files
Fixes CCXDEV-9161
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.

remove duplicate table in config

---

differ/renderer.go

Log the response body if cannot be unmarshalled
Unit tests.

[CCXDEV-10291] Log the response body if cannot be unmarshalled

---

differ/differ.go

Forgot to run this in a goroutine.

[CCXDEV-10291] Push metrics in loop in the main function in goroutine

---

deploy/clowdapp.yaml

log also the `... service-log` pods
- n/a

log also service-log

---

ccx_notification_service.go
config.toml
deploy/clowdapp.yaml

don't output logs to stderr
Fixes #CCXDEV-9436
- n/a

don't output logs to stderr

---

differ/comparator.go

More of a refactor than a fix, but this way we ensure the log clearly indicates the resolution reasonnn
CI

Fix log of issue comparison result

---

go.mod
go.sum

Bump-up `testify` library
Just test

Bump up `testify` library

---

go.mod
go.sum

Bump-up `zerolog` library
Will be checked on CI.

Bump-up `zerolog` library

---

.gitignore
go.mod
go.sum

Bump up aggregator data library
To be done on CI

Bump up aggregator data library

---

go.mod
go.sum

Bump-up OCM SDK Go library
To be checked on CI

Bump-up OCM SDK Go library

---

README.md

Added Go badge.
Fixes #431
N/A

Fixed issue #431

---

differ/differ.go
producer/kafka/kafka_producer.go
producer/servicelog/service_log_producer.go
producer/servicelog/service_log_producer_test.go

Pass consumer configuration by reference

Pass consumer configuration by reference

---

differ/differ.go
differ/export_test.go
differ/metrics.go
differ/metrics_test.go

Pass metrics configuration by reference

Pass metrics configuration by reference

---

differ/content.go
differ/differ.go
differ/storage.go
tests/mocks/Storage.go

Pass `configuration` and `report` by reference in all sources

Pass configuration and report by reference in all sources

---

differ/export_test.go
differ/metrics_test.go

Refactoring: PushMetrics function

Refactoring: PushMetrics function

---

differ/comparator.go
differ/differ.go
differ/differ_test.go
differ/storage.go

Updated log levels for selected messages
https://issues.redhat.com/browse/CCXDEV-11608
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.

[CCXDEV-11608] Updated log leves

---

README.md
differ/comparator.go
differ/comparator_test.go
differ/differ.go
differ/differ_cli_args_test.go
differ/differ_test.go
types/types.go

Remove weekly notification support, as it is not compatible with the notification aggregator.
Fixes CCXDEV-6961 partially
N/A

Remove weekly notifications support

---

.travis.yml
docs/demos/dsl-events-filtering/shunting_yard.go

Bump-up Go version on CI to 1.20

Bump-up Go version on CI to 1.20

---

producer/kafka/kafka_producer.go

- Structured messages in Kafka producer
- Reduce duplicated glitchtip errors
To be tested on CI.

Structured messages in Kafka producer

---

types/types_test.go

Added missing unit tests for `types` module
Fixes CCXDEV-10724
Fixes CCXDEV-10725

Added missing unit tests for types module

---

conf/configuration_test.go
conf/export_test.go

Added missing unit tests for `conf` module
Fixes #498 
Fixes #499 
Fixes #505

Added missing unit tests for conf module

---

producer/servicelog/service_log_producer.go
producer/servicelog/service_log_producer_test.go

Fix panic when wrong URL is configured
Fixes https://issues.redhat.com/browse/CCXDEV-11941

Fix panic when wrong URL is configured

---

producer/servicelog/service_log_producer_test.go

Unit test: construct `ServiceLog` producer on error

Unit test: construct ServiceLog producer on error

---

differ/storage_test.go

NewStorage unit tests

---

go.mod
producer/kafka/export_test.go
producer/kafka/kafka_producer.go
producer/kafka/kafka_producer_test.go
producer/kafka/scram_client.go

New authentication mechanism enabled
Fixes CCXDEV-11964
- Added unit tests to cover new code
- Will test actual deployment in stage with clowder deployment

Add support for SCRAM-SHA512 to Kafka producer

---

gosec.sh

Install specific `gosec` version

Install specific `gosec` version

---

differ/storage_test.go

Unit tests for `storage.Cleanup`
Fixes #539

Unit tests for `storage.Cleanup`

---

differ/storage_test.go

Unit tests for `storage.CleanupNewReports`
Fixes #540 

Unit tests for `storage.CleanupNewReports`

---

differ/storage_test.go

Unit tests for `storage.DeleteRowFromNewReports`
Fixes #534 

Unit tests for `storage.DeleteRowFromNewReports`

---

differ/storage_test.go

Unit tests for `storage.DeleteRowFromReported`
Fixes #535 

Unit tests for `storage.DeleteRowFromReported`

---

differ/storage_test.go

Unit tests for method `storage.ReadNotificationTypes`
Fixes #531 

Unit tests for method `storage.ReadNotificationTypes`

---

differ/storage_test.go

Unit tests for method `storage.PrintNewReports`
Fixes #537 

Unit tests for method `storage.PrintNewReports`

---

differ/storage_test.go

Unit test: `Storage.Close` method
Fixes #513 

Unit test: `Storage.Close` method

---

differ/storage_test.go

Unit test for method `storage.PrintNewReportsForCleanup`
Fixes #520 

Unit test for method `storage.PrintNewReportsForCleanup`

---

differ/content_test.go

Improved fetchall unit tests

---

differ/storage.go

Don't close row set twice
(already covered by unit tests)
To be re-checked on CI.

Don't close row set twice

---

differ/storage_test.go

Unit tests for method `Storage.WriteNotificationRecordImpl`
Fixes #532 

Unit tests for method `Storage.WriteNotificationRecordImpl`

---

differ/cli_test.go
differ/export_test.go

Add unit tests for deleteOperationSpecified
locally

[CCXDEV-10742 ] Add unit tests for deleteOperationSpecified

---

differ/comparator_test.go
differ/differ_test.go
differ/export_test.go

Increase UT coverage
Fixes [#517](https://github.com/RedHatInsights/ccx-notification-service/issues/517)
CI

[CCXDEV-10750] Cover setupNotificationTypes function

---

differ/service_log_test.go

In between checkouts and pushes, this file with the unit tests for modified service log-related functionality got forgotten...
CI

Push service log unit tests

---

differ/storage_test.go

Unit tests for `storage.WriteNotificationRecord`
Fixes #515 

Unit tests for `storage.WriteNotificationRecord`

---

differ/cleaner_test.go
differ/export_test.go

Unit tests for function `printNewReportsForCleanup`
Fixes #507 

Unit tests for function `printNewReportsForCleanup`

---

Dockerfile

Update base images used in Dockerfile to newer versions.
Built the image locally.

[CCXDEV-11994] Update base images used in Dockerfile

---

.github/workflows/dependabot-automerge.yml

Reverts https://github.com/RedHatInsights/ccx-notification-service/pull/721

[CCXDEV-12378] Reenable dependabot-automerge.yml

---

dashboards/grafana-dashboard-ccx-notification-service.configmap.yaml

Change metrics datasource used in production, because it has been changed by app-sre.
Dashboard configuration was copied from stage Grafana.

Fix dashboard datasource

---

dashboards/grafana-dashboard-ccx-notification-service.configmap.yaml

The stage Prometheus pushgateway datasource changed both for stage and prod a few weeks ago. We updated the prod datasource in the dashboard but forgot about the stage one.
Manually in the UI.

[CCXDEV-12786][dashboard] Fix stage datasource

---

pr_check.sh

Add relevant IQE tests that should be run in PR check.
Check that the CI runs successfully with new tests.

[CCXDEV-9711] Add notifications IQE tests to PR check

---

deploy/clowdapp.yaml

Currently I cannot modify the SSO URL used in service log for token refreshment.
NA

[CCXDEV-9710] Add service log token URL param

---

pr_check.sh

Add service log tests to PR check
CI job with testing passed

[CCXDEV-9710] Add servicelog tests to PR check

---

cmd/ccx-notification-service/main.go
differ/differ.go

Removing the testing error logs for glitchtip

Removing the testing error logs for glitchtip

---

differ/comparator.go
differ/content.go
differ/renderer.go
differ/storage.go
producer/servicelog/service_log_producer.go

Trying to avoid Glitchtip duplicates.
CI

[CCXDEV-14052] Remove formated error logs

---

goerrcheck.sh
ineffassign.sh
pr_check.sh

Linters fix

---

dashboards/grafana-dashboard-ccx-notification-service.configmap.yaml

It changed: https://redhat-internal.slack.com/archives/CCRND57FW/p1734095102346809

Fix outdated prometheus datasource

---

.github/workflows/gotests.yaml
README.md

The codecov.io is out of date because we are no longer pushing the coverage there.
This CI.

[CCXDEV-15082] fix codecov.io

---

.tekton/notification-service-push.yaml

The `apply-tags` task on the Tekton configuration files needs to be updated in both on-pull-request and on-push configuration files. I missed the later, so this PR fixes this problem.
N/A

Fix on-push job configuration

---

.tekton/notification-service-pull-request.yaml
.tekton/notification-service-push.yaml

Konflux tektone task reference update

Konflux tektone task reference update

---

dashboards/grafana-dashboard-ccx-notification-service.configmap.yaml

As a follow up of https://github.com/RedHatInsights/ccx-notification-service/pull/989:
1. Added a state panel in order to visualize the different processes in the cronjobs
2. Added the time it takes to run each process
3. Remove the `rate` calculation from the rest of the panels as it's missleading. This way we will be able to tell the exact number of notifications sent in every execution for example.
Let's be honest, the information shown was quite useless...
Stage UI.

[CCXDEV-15375] conf: update dashboard
